# Generated by Django 4.0.2 on 2022-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
