# Generated by Django 4.0.2 on 2022-02-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_image_ppoi_account_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
