# Generated by Django 4.0.2 on 2022-02-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_owner',
        ),
    ]
