# Generated by Django 4.0.2 on 2022-02-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image_ppoi',
        ),
    ]
