# Generated by Django 4.0.2 on 2022-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_image_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
    ]
