# Generated by Django 4.0.2 on 2022-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postcategory_alter_post_options_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='AccountProfilePicture',
        ),
    ]
