# Generated by Django 4.0.2 on 2022-02-23 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_postreaction_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreaction',
            old_name='post',
            new_name='xost',
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.CharField(choices=[('+', 'Like'), ('-', 'Dislike')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('author', 'xost')},
        ),
    ]
