# Generated by Django 4.0.2 on 2022-02-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_xost_postreaction_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='is_active',
        ),
    ]
